apiVersion: v1
kind: ConfigMap
metadata:
  name: country-info-config
  namespace: country-info
data:
  SERVER_PORT: "8080"
  SOAP_WSDL_URL: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  LOGGING_LEVEL_COM_COUNTRY_INFO: "INFO"
